services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql+pymysql://root:password@db:3306/pearltours
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pearltours
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"  # Avoid host port conflict
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-password"]
      interval: 5s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  mysql_data: